Description: "Provision Cloud9"
Resources:
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      ImageId: amazonlinux-2-x86_64
      InstanceType: t3.small
      OwnerArn: !Sub "arn:aws:sts::${AWS::AccountId}:assumed-role/TeamRole/MasterKey"
      Repositories:
        - PathComponent: /nextflow-demo
          RepositoryUrl: https://github.com/sebastianlzy/nextflow-demo.git


 